name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Setup do Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Instalar dependências
      run: npm install

    - name: Compilar o contrato
      run: npx hardhat compile

    - name: Executar os testes
      run: npx hardhat test
